// Lucide icons, copied into the build by the `assets` glob in angular.json. Keep both lists in sync.
export type IconName =
    | 'audio-lines'
    | 'bike'
    | 'cloud'
    | 'cloud-drizzle'
    | 'cloud-fog'
    | 'cloud-hail'
    | 'cloud-lightning'
    | 'cloud-moon'
    | 'cloud-moon-rain'
    | 'cloud-rain'
    | 'cloud-rain-wind'
    | 'cloud-snow'
    | 'cloud-sun'
    | 'cloud-sun-rain'
    | 'flower-2'
    | 'moon'
    | 'snowflake'
    | 'sparkles'
    | 'sun'
    | 'sunset'
    | 'trees'
    | 'triangle-alert'
    | 'umbrella'
    | 'wheat'
    | 'wind';
